### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gigawatts** [d99kris/idntag#3]
After installing dependencies ( including the missing mp3info tool, as I've mentioned here https://github.com/d99kris/idntag/issues/1#issuecomment-569118762 ) and successfully building idntag, it fails to fingerprint any file, including the 'tests/song.mp3' file included in the repo.

```
./idntag -k ../tests/song.mp3
idntag/build/../tests/song.mp3 : FAIL : fingerprint generation error
```

I'm testing this from Ubuntu 16.04.6

**Comment by d99kris** [comment]
Hi - thanks for reporting the issue. I believe the original documentation was not correct, so I've updated it to reflect what's done for the Travis CI job (based on .travis.yml). I suspect this will fix the issue. Please let me know if you're still facing issues.

**Comment by magdesign** [comment]
thanks for this tool. 
however, i also get this error on some tracks:
`
Avatar - Soundtracks (2009) (OST) (mrsjs)/Album Info.nfo : FAIL : fingerprint generation error`

on alpine linux. some tracks work, some dont.

**Comment by d99kris** [comment]
Hi @magdesign - I believe the issue you encountered is different from this original bug report. Your issue is likely that idntag tries to fingerprint non-audio files (like `Album Info.nfo`). In b0bd596 / `v1.14` I've restricted processing to supported file types only. Please try it out and let me know in case you still encounter issues (ideally reporting a new issue).
